name: build-image
on:
  workflow_dispatch:
    inputs:
      nebula_version:
        description: 'Nebula version'
        required: true
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        id: checkout
        name: Checkout
        uses: actions/checkout@v3
      -
        id: set_up_qumu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        id: set_up_docker_buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        id: login_to_dockerhub
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        id: build_and_push
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nebula:${{ inputs.nebula_version }}
          build-args: |
            NEBULA_VERSION=${{ inputs.nebula_version }}
